# Prd environment (SYNTHETIC DEMO). Requires manual approval.
parameters:
  - name: serviceName
    type: string
  - name: buildConfiguration
    type: string
    default: 'Release'
  - name: releaseChannel
    type: string
    default: 'stable'
  - name: dependsOnStage
    type: string
    default: BuildAndTest

stages:
  - template: ../deploy-environment-stage.yml
    parameters:
      environmentName: Production
      serviceName: ${{ parameters.serviceName }}
      buildConfiguration: ${{ parameters.buildConfiguration }}
      releaseChannel: ${{ parameters.releaseChannel }}
      dependsOnStage: ${{ parameters.dependsOnStage }}
      requireApproval: true
